Download job data in advance
iterait/shepherd pull request #93
Opened 2019-08-07 12:56 UTC by Teyras

2019-08-13 21:22 UTC, blazekadam reviewed
This looks good so far and the tests are passing but I will need to think a bit more about it. I am afraid of additional edge cases and race conditions...

2019-08-13 21:22 UTC, blazekadam commented on shepherd/shepherd/shepherd.py
> +        Slaughter a sheep and resurrect it with a different model.
Whoa a resurrection 👍

2019-08-14 06:44 UTC, Teyras commented
@blazekadam Sure, take your time - this is nice to have, but not essential by any means.

2019-08-27 07:19 UTC, blazekadam requested changes

2019-08-27 07:19 UTC, blazekadam commented on shepherd/shepherd/shepherd.py
> +        self._prepare_job_dir_queue = TaskQueue(worker_count=8)
What an arbitrary constant?

2019-08-27 07:19 UTC, blazekadam commented on shepherd/shepherd/shepherd.py
> +                        # if necessary, cancel input downloads
The jobs should be imo canceled before the `rmtree`

2019-08-27 07:19 UTC, blazekadam commented on shepherd/shepherd/shepherd.py
> +        # we need to wait for the in-progress jobs which might already be in the socket
What a respectful way to slaughter a sheep :o

2019-08-27 07:19 UTC, blazekadam commented on shepherd/shepherd/shepherd.py
> +        except SheepConfigurationError as sce:
The `except` clauses looks quite similar, can we join them or is there a good reason to keep them separated?

2019-08-27 07:19 UTC, blazekadam commented on shepherd/shepherd/shepherd.py
> +                    logging.critical(f"Task that should have pulled data for job `{job_id}` mysteriously disappeared")
This may happen anytime a sheep is purged with `health_check`, I do not think that it deserves the `critical` level...

2019-08-27 07:19 UTC, blazekadam commented on shepherd/shepherd/shepherd.py
> +                # notify the queue that the task is done
This is weird wording (line 303 as well), the job is certainly not done, it was just sent for processing

2019-08-27 07:19 UTC, blazekadam commented on shepherd/shepherd/shepherd.py
> +            status = self._job_status.pop(job_id)
Same as the line 356, can we put it before the `if-else`?

2019-08-27 07:19 UTC, blazekadam commented on shepherd/shepherd/shepherd.py
> +            status.status = JobStatus.DONE
I do not like how `DoneMessage` is processed in place while `ErrorMessage` is mostly handled with `self._report_job_failed`. I.e., we do quite the same at two different places and two different depths...

2019-09-18 17:52 UTC, blazekadam commented
Nothing really waits for this, right?

2019-09-19 06:43 UTC, Teyras commented
That's right

2024-10-30 15:44 UTC, closed without merging